### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by Sara-Samer** [abdoafage/Udemy-React-Clone#1]
this code can be reduced using `map`
https://github.com/abdoafage/Udemy-React-Clone/blob/d6646970cab6eff0ab5677460aed37abde2ed2a6/src/component/CoursesPart/CoursesSection.js#L15-L130

**Comment by abdoafage** [comment]
I fixed this issue in this commit -> 8ee31a446f5246eb7a88a73d1fee560e8f1b8e2d
